### ISSUE TITLE
How can a curve move vertically upward in a region where neighboring slope ticks are not even close to vertical?

### ISSUE THREAD

**Issue by imrek** [nathangrigg/slopefield#2]
Consider y'= (t^2)/(1+y^3) and the region around t=-8 and y=5. The neighboring slope ticks and the slope of the curve are clearly contradictory to each other.

http://slopefield.nathangrigg.net/?fn=%28t^2%29%2F%281%2By^3%29&tmin=-20&tmax=20&tticks=40&ymin=-25.0&ymax=25.0&yticks=40&t0=-8.0&y0=0.0&step=0.1&drawsol=on

**Comment by nathangrigg** [comment]
The is the limitation of numerical approximation. The approximation it uses will look at the slope, move a certain distance, and then look at the slope again, repeat. The problem in this example is that it overshoots on the first step. Try making the step size smaller and it does a better job. 

There are better approximations than the one I use that would handle this particular case, but in general this is a difficult problem to solve. Math is never as easy as the textbooks lead us to believe.
